#!/usr/bin/env bash

set -e

usage="Usage: $0 <version> <output-file>"

version=${1?$usage}
file=${2?$usage}

cat > $file << EOT
openapi: 3.0.3

info:
  title: Grafana Dashboard Spec
  version: $version

paths: {}

components:
  schemas:
EOT

for f in $(find specs/$version -type f -name "[[:upper:]]*"); do
  cat $f | sed 's/^/    /' >> $file
done
